[package]
name = "utils"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
doctest = false

[dependencies]
primitives = { path = "../primitives" }
k256 = { version = "0.13", features = ["ecdsa"] }
serde = { version = "1", features = ["derive"] }
alloy = { version = "1.6.0", features = ["full"] }
uuid = { version ="1.19", features = ["v4", "serde"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde_json = "1.0.149"
hex = "0.4"
rlp = "0.6.1"
thiserror = "2.0.18"
dashmap = "6.1.0"
zeroize = "1.8.2"
sha3 = "0.10"
fastrand = "2.4"
url = "2.5.8"
