[workspace]
resolver = "3"

members = ["client"]

[workspace.dependencies]
lobby = { path = "../ensemble/lobby" }
actors = { path = "../ensemble/crate/actors" }
cortex = { path = "../ensemble/crate/cortex" }
kernel = { path = "../ensemble/crate/kernel" }
utils = { path = "../ensemble/crate/utils" }
