[package]
name = "lobby"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
kernel = {path = "../crate/kernel"}
netio = {path = "../crate/netio"}
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "postgres",
] }
uuid = { version ="1.19", features = ["v4", "serde"] }
dashmap = "6.1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry"] }
