[package]
name = "actors"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "postgres",
] }
kernel = { path = "../kernel" }
alloy-primitives = {version = "1.5.2", features = ["serde"]}
async-trait = "0.1.89"
