[package]
name = "lobby"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
primitives = { path = "../crate/primitives" }
utils = { path = "../crate/utils" }
actors = { path = "../crate/actors" }
cortex = { path = "../crate/cortex" }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["trace"] }
alloy = { version = "1.6.0", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi"] }
tracing-forest = { version = "0.3", features = ["tokio", "ansi"] }
uuid = { version = "1.19", features = ["v4", "serde"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres",] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
dashmap = "6.1.0"
tracing = "0.1"
axum = "0.8.8"

[dev-dependencies]
testcontainers-modules = { version = "0.15", features = ["postgres", "redis", "anvil"] }
reqwest = { version = "0.12", features = ["json"] }
rand = "0.8"